# This is a basic workflow to help you get started with Actions

name: Build and Push Docker Image for FastAPI Backend

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
    PROJECT_NAME: aoaiwkshp-backend
    PROJECT_SUBPATH: agentic_ai/
    SPECIFIC_RELEASE_TAG: ${{ vars.SPECIFIC_RELEASE_TAG || '' }}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Only run if the required variables exist
    if: vars.REGISTRY_LOGIN_SERVER != '' && vars.REGISTRY_LOGIN_SERVER != null

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
            if [ -z "${{ env.SPECIFIC_RELEASE_TAG }}" ]; then
                docker build ${{ vars.PROJECT_SUBPATH }} -t ${{ vars.REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME }}:${{ github.sha }} -t ${{ vars.REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME }}:latest
            else
                docker build ${{ vars.PROJECT_SUBPATH }} -t ${{ vars.REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME }}:${{ env.SPECIFIC_RELEASE_TAG }} -t ${{ vars.REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME }}:latest
            fi

      - run: |
          docker push ${{ vars.REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME }} --all-tags
